jira:
        server: https://tarsier02.atlassian.net
        username: rajiv.gangadharan@gmail.com
        password: Q1w2e3r4%

project:
        - key: <<JIRA Project key>>
          name: <<Name of the JIRA Project>>
          board: 6597
          team: 13920
        - key: <<Jira Project KEY>>
          name: <<Name of the JIRA Project>>
          board: 6497
          team: 13998
